const actionTypes = {
    CART_ADD_EL: 'CART_ADD_El',
    CART_REM_EL: 'CART_REM_EL',
    CART_SAVE_BUY:'CART_SAVE_BUY',
    CART_ALL_DEL: 'CART_ALL_DEL',

    USER_LOG_REQ: 'USER_LOG_REQ',
    USER_LOG_SUCCESS: 'USER_LOG_SUCCESS',
    USER_LOG_FAIL: 'USER_LOG_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_REG_REQ: 'USER_REG_REQ',
    USER_REG_SUCCESS: 'USER_REG_SUCCESS',
    USER_REG_FAIL: 'USER_REG_FAIL',
    USER_ALL_FORADM_REQ: 'USER_ALL_FORADM_REQ',
    USER_ALL_FORADM_SUCCESS: 'USER_ALL_FORADM_SUCCESS',
    USER_ALL_FORADM_FAIL: 'USER_ALL_FORADM_FAIL',
    USER_ALL_FORADM_RESET: 'USER_ALL_FORADM_RESET',
    USER_DEL_FORADM_REQ: 'USER_DEL_FORADM_REQ',
    USER_DEL_FORADM_SUCCESS: 'USER_DEL_FORADM_SUCCESS',
    USER_DEL_FORADM_FAIL: 'USER_DEL_FORADM_FAIL',
    USER_CHANGE_FORADM_REQ: 'USER_CHANGE_FORADM_REQ',
    USER_CHANGE_FORADM_SUCCESS: 'USER_CHANGE_FORADM_SUCCESS',
    USER_CHANGE_FORADM_FAIL: 'USER_CHANGE_FORADM_FAIL',
    USER_CHANGE_FORADM_RESET: 'USER_CHANGE_FORADM_RESET',

    USER_FORGOT_REQ:'USER_FORGOT_REQ',
    USER_FORGOT_SUCCESS: 'USER_FORGOT_SUCCESS',
    USER_FORGOT_FAIL: 'USER_FORGOT_FAIL',

    USER_SUBMIT_REQ:'USER_SUBMIT_REQ',
    USER_SUBMIT_SUCCESS:'USER_SUBMIT_SUCCESS',
    USER_SUBMIT_FAIL:'USER_SUBMIT_FAIL',

    USER_PARAM_REQ:'USER_PARAM_REQ',
    USER_PARAM_SUCCESS: 'USER_PARAM_SUCCESS',
    USER_PARAM_FAIL: 'USER_PARAM_FAIL',
    USER_PARAM_RESET: 'USER_PARAM_RESET',

    USER_UPDPROF_REQ:'USER_UPDPROF_REQ',
    USER_UPDPROF_SUCCESS: 'USER_UPDPROF_SUCCESS',
    USER_UPDPROF_FAIL: 'USER_UPDPROF_FAIL',
    USER_UPDPROF_RESET: 'USER_UPDPROF_RESET',
    USER_RESET_RESET: 'USER_RESET_RESET',

    CAPSULE_DEL_REQ: 'CAPSULE_DEL_REQ',
    CAPSULE_DEL_SUCCESS: 'CAPSULE_DEL_SUCCESS',
    CAPSULE_DEL_FAIL: 'CAPSULE_DEL_FAIL',
    CAPSULE_DEL_RESET: 'CAPSULE_DEL_RESET',

    CAPSULE_COMM_REQ: 'CAPSULE_COMM_REQ',
    CAPSULE_COMM_SUCCESS: 'CAPSULE_COMM_SUCCESS',
    CAPSULE_COMM_FAIL: 'CAPSULE_COMM_FAIL',
    CAPSULE_COMM_RESET: 'CAPSULE_COMM__RESET',

    CAPSULE_MADE_NEW_REQ: 'CAPSULE_MADE_NEW_REQ',
    CAPSULE_MADE_NEW_SUCCESS: 'CAPSULE_MADE_NEW_SUCCESS',
    CAPSULE_MADE_NEW_FAIL: 'CAPSULE_MADE_NEW_FAIL',
    CAPSULE_MADE_NEW_RESET: 'CAPSULE_MADE_NEW_RESET',

    CAPSULE_SET_REQ: 'CAPSULE_SET_REQ',
    CAPSULE_SET_SUCCESS: 'CAPSULE_SET_SUCCESS',
    CAPSULE_SET_FAIL: 'CAPSULE_SET_FAIL',
    CAPSULE_SET_RESET: 'CAPSULE_SET_RESET',

    MADE_ORDER_REQ:'MADE_ORDER_REQ',
    MADE_ORDER_SUCCESS:'MADE_ORDER_SUCCESS',
    MADE_ORDER_FAIL:'MADE_ORDER_FAIL',

    ORDER_ID_REQ:'ORDER_ID_REQ',
    ORDER_ID_SUCCESS:'ORDER_ID_SUCCESS',
    ORDER_ID_FAIL:'ORDER_ID_FAIL',

    ORDER_PAID_REQ:'ORDER_PAID_REQ',
    ORDER_PAID_SUCCESS:'ORDER_PAID_SUCCESS',
    ORDER_PAID_FAIL:'ORDER_PAID_FAIL',
    ORDER_PAID_RESET:'ORDER_PAID_RESET',

    ORDERS_SEE_PAID_REQ:'ORDERS_SEE_PAID_REQ',
    ORDERS_SEE_PAID_SUCCESS:'ORDERS_SEE_PAID_SUCCESS',
    ORDERS_SEE_PAID_FAIL:'ORDERS_SEE_PAID_FAIL',
    ORDERS_SEE_PAID_RESET:'ORDERS_SEE_PAID_RESET',

    ORDERS_ALL_REQ:'ORDERS_ALL_REQ',
    ORDERS_ALL_SUCCESS:'ORDERS_ALL_SUCCESS',
    ORDERS_ALL_FAIL:'ORDERS_ALL_FAIL',
}
export default actionTypes
