const actionTypes = {
    CART_ADD_EL: 'CART_ADD_El',
    CART_REM_EL: 'CART_REM_EL',

    USER_LOG_REQ: 'USER_LOG_REQ',
    USER_LOG_SUCCESS: 'USER_LOG_SUCCESS',
    USER_LOG_FAIL: 'USER_LOG_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_REG_REQ: 'USER_REG_REQ',
    USER_REG_SUCCESS: 'USER_REG_SUCCESS',
    USER_REG_FAIL: 'USER_REG_FAIL'
}
export default actionTypes
