const actionTypes = {
    CART_ADD_EL: 'CART_ADD_El',
    CART_REM_EL: 'CART_REM_EL',
    CART_SAVE_BUY:'CART_SAVE_BUY',
    CART_ALL_DEL: 'CART_ALL_DEL',

    USER_LOG_REQ: 'USER_LOG_REQ',
    USER_LOG_SUCCESS: 'USER_LOG_SUCCESS',
    USER_LOG_FAIL: 'USER_LOG_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_REG_REQ: 'USER_REG_REQ',
    USER_REG_SUCCESS: 'USER_REG_SUCCESS',
    USER_REG_FAIL: 'USER_REG_FAIL',

    USER_FORGOT_REQ:'USER_FORGOT_REQ',
    USER_FORGOT_SUCCESS: 'USER_FORGOT_SUCCESS',
    USER_FORGOT_FAIL: 'USER_FORGOT_FAIL',

    USER_RESET_REQ:'USER_RESET_REQ',
    USER_RESET_SUCCESS: 'USER_RESET_SUCCESS',
    USER_RESET_FAIL: 'USER_RESET_FAIL',

    USER_PARAM_REQ:'USER_PARAM_REQ',
    USER_PARAM_SUCCESS: 'USER_PARAM_SUCCESS',
    USER_PARAM_FAIL: 'USER_PARAM_FAIL',

    USER_UPDPROF_REQ:'USER_UPDPROF_REQ',
    USER_UPDPROF_SUCCESS: 'USER_UPDPROF_SUCCESS',
    USER_UPDPROF_FAIL: 'USER_UPDPROF_FAIL',
    USER_UPDPROF_RESET: 'USER_UPDPROF_RESET',
    USER_RESET_RESET: 'USER_RESET_RESET',

    CAPSULE_COMM_REQ: 'CAPSULE_COMM_REQ',
    CAPSULE_COMM_SUCCESS: 'CAPSULE_COMM_SUCCESS',
    CAPSULE_COMM_FAIL: 'CAPSULE_COMM_FAIL',
    CAPSULE_COMM_RESET: 'CAPSULE_COMM__RESET',

    MADE_ORDER_REQ:'MADE_ORDER_REQ',
    MADE_ORDER_SUCCESS:'MADE_ORDER_SUCCESS',
    MADE_ORDER_FAIL:'MADE_ORDER_FAIL',

    ORDER_ID_REQ:'ORDER_ID_REQ',
    ORDER_ID_SUCCESS:'ORDER_ID_SUCCESS',
    ORDER_ID_FAIL:'ORDER_ID_FAIL',


}
export default actionTypes
